name: Racket CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Racket environment
      uses: Bogdanp/setup-racket@v1.7
      with:
          version: 8.3

    - name: Build
      run:  |
        cd mini-compiler
        raco make benchmarks.rkt

    - name: Test
      run:  |
        racket benchmarks.rkt

